### ISSUE TITLE
Unable to get the overlay to display

### ISSUE THREAD

**Issue by longestdrive** [CarlosBonetti/jquery-loading#6] opened 2015-10-15 16:33 UTC
Hi

I'm having problems getting the overlay to display correctly.

I have a table with an id of `'#rounds'` I've initiated the plug in using: 
    $('#rounds').loading();

At this point I can see the div loading within the elements at the base of the page (in chrome developer tools) which looks like this:

```
<div class="loading-overlay loading-theme-light loading-shown" style="display: none; position: absolute; z-index: 1; top: 280px; left: 9px; width: 923px; height: 123px;" id="rounds_loading-overlay"><div class="loading-overlay-content">Loading...</div></div>
```

I'm trying to use the overlay in a click event.

```
$('.delete-row').click(function (e) {
            $('#rounds').loading();
            e.preventDefault();
            submitDeleteRequest($(this))
        });
```

I've tried as a test to place it in the doc ready, it only displays if I move my mouse away from the main page element, into say chromes toolbar at the top or a side menu in the page. Otherwise It's not visible - strange

Am I missing something?

I'm using ver 1.10

Thanks

**Comment by CarlosBonetti** [comment] 2015-10-17 22:31
Hi @longestdrive. That's a very strange behaviour, it's hard to tell what's causing it. Any chance of creating a live example reproducing the error?

**Comment by CarlosBonetti** [comment] 2016-11-01 13:10
Closing since there was no update on this issue

**Closed by CarlosBonetti** 2016-11-01 13:10 UTC
